version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cinematch
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ../backend/db:/docker-entrypoint-initdb.d:ro

  app:
    build:
      context: ..          # one level up from .devcontainer
      dockerfile: .devcontainer/Dockerfile
    user: root
    volumes:
      - ..:/workspace        # mount entire project root
      - backend_node_modules:/workspace/backend/node_modules
    working_dir: /workspace/backend
    env_file:
      - ../backend/.env      # ensure .env.example exists; instruct collaborators to copy
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: npm run dev    # uses nodemon for live reload

volumes:
  db_data:
  backend_node_modules:
